MIS_CONSTANT = 'MIS('
MIS_START_CONSTANT = '('
MIS_STOP_CONSTANT = ')'
EQUALS_OPERATOR = '='
CURLY_BRACE_OPENING = "{"
CURLY_BRACE_CLOSING = "}"
COMMA_OPERATOR = ","
SDC_CONSTANT = 'SDC'
ROUND_FLOAT_DIGITS = 2
CANNOT_BE_TOGETHER = 'cannot_be_together'
MUST_HAVE = 'must-have'
SPACE = ' '
SQUARE_BRACKET_OPENING = '['
SQUARE_BRACKET_CLOSING = ']'
